# Generated by Django 5.0.2 on 2024-05-28 08:28
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_userprofile_user_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(
                choices=[
                    ('truck_1', '1 Ton Truck'),
                    ('truck_1.5', '1.5 Ton Truck'),
                    ('truck_2', '2 Ton Truck'),
                    ('truck_4', '4 Ton Truck'),
                    ('bakkie', 'Bakkie'),          # Added
                    ('truck_8', '8 Ton Truck')     # Added
                ],
                default='truck_1',  # Changed from 'Bike' to valid default
                max_length=100
            ),
        ),
    ]
