# Generated by Django 5.0.2 on 2025-03-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0013_driver_accepted_trips_driver_total_trips"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("truck_1", "1 Ton Truck"),
                    ("truck_1.5", "1.5 Ton Truck"),
                    ("truck_2", "2 Ton Truck"),
                    ("truck_4", "4 Ton Truck"),
                    ("bakkie", "Bakkie"),
                    ("truck_8", "8 Ton Truck"),
                ],
                default="truck_1",
                max_length=100,
            ),
        ),
    ]
