
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - Toota

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          cd server
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          cd server 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static
        run: |
          cd server
          python manage.py collectstatic --noinput

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: Zip artifact for deployment
        run: |
          cd server
          zip release.zip ./* -

      - name: Run database migrations
        run: |
          cd server  # Ensure the command is run in the "server" directory
          python manage.py migrate  # Runs migrations as the final deployment step