on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          cd server
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          cd server
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static files
        run: |
          cd server
          python manage.py collectstatic --noinput

      - name: Zip artifact for deployment
        run: |
          cd server
          zip -r ../release.zip ./*

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip  # Ensure correct path to release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .  # Downloads release.zip to the current directory

      - name: Unzip artifact for deployment
        run: unzip release.zip -d .  # Unzips release.zip content to root directory

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'Toota'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D6A79DE623AD4EFDA432A730767F3134 }}
          package: .  # Deploys the current directory
          verbose: true  # Enables detailed logging for debugging

      - name: Run database migrations
        run: |
          cd server
          python manage.py migrate  # Runs migrations after deployment
