name: Build and deploy Node.js app to Azure Web App - client-toota

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies and build the app
        run: |
          npm install
          npm run build
          ls -la dist
        working-directory: client

      - name: Verify dist folder
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist folder not found!";
            exit 1;
          fi
        working-directory: client

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip dist
        working-directory: client

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: client/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Debug: Check deployment contents
        run: ls -la dist

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'client-toota'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_211FC37D921247F68A1196135695E3E9 }}
          package: ./dist