name: Build and deploy Python app to Azure Web App - Toota

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files and directories
        run: |
          ls -R > directory_structure.txt
          cat directory_structure.txt

      - name: Check for server directory
        id: check_server
        run: |
          if [ -d "server" ]; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        if: env.exists == 'true'
        run: |
          cd server
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        if: env.exists == 'true'
        run: |
          cd server
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        if: env.exists == 'true'
        run: |
          cd server
          zip -r ../release.zip ./*
          
      - name: Verify the artifact creation
        if: env.exists == 'true'
        run: ls -l ../release.zip

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        if: env.exists == 'true'
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Create server directory
        run: mkdir -p server

      - name: Move artifact to server directory
        run: mv release.zip server/

      - name: Unzip artifact for deployment
        run: |
          cd server
          unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'Toota'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_598317C082D04CCEA9BABEDD8AABBF64 }}